import type { CatalogArchetype } from "./buildSchema.js";

export interface CatalogItemDef {
  name: string;
  description: string;
  archetype?: CatalogArchetype;
}

export interface ComponentGroupDef {
  id: string;
  label: string;
  icon: string;
  defaultArchetype: CatalogArchetype;
  items: CatalogItemDef[];
}

function item(name: string, description: string, archetype?: CatalogArchetype): CatalogItemDef {
  return archetype ? { name, description, archetype } : { name, description };
}

export const COMPONENT_GROUPS: ComponentGroupDef[] = [
  {
    id: "buttons",
    label: "Button Components",
    icon: "🔘",
    defaultArchetype: "button",
    items: [
      item("Button", "Generic configurable button"),
      item("PrimaryButton", "Main call-to-action button"),
      item("SecondaryButton", "Secondary action button"),
      item("IconButton", "Icon-only action button"),
      item("LoadingButton", "Button with loading state"),
      item("Fab", "Floating action button"),
      item("ToggleButton", "Toggle on/off button"),
      item("SplitButton", "Button with dropdown split"),
      item("DropdownButton", "Button with attached menu"),
    ],
  },
  {
    id: "forms",
    label: "Form Components",
    icon: "📝",
    defaultArchetype: "form",
    items: [
      item("Input", "Text input field"),
      item("PasswordInput", "Masked password field"),
      item("Textarea", "Multi-line text input"),
      item("NumberInput", "Numeric input with steppers"),
      item("EmailInput", "Email address field"),
      item("SearchInput", "Search query field"),
      item("PhoneInput", "Phone number with formatting"),
      item("OtpInput", "One-time password digits"),
      item("Select", "Dropdown select", "form-select"),
      item("MultiSelect", "Multiple selection dropdown", "form-select"),
      item("AsyncSelect", "Remote-loaded select", "form-select"),
      item("Checkbox", "Boolean checkbox", "form"),
      item("RadioButton", "Single choice radio", "form"),
      item("ToggleSwitch", "On/off switch", "form"),
      item("RangeSlider", "Numeric range slider", "form"),
      item("DatePicker", "Calendar date picker", "form"),
      item("TimePicker", "Time selection control", "form"),
      item("DateRangePicker", "Start/end date range", "form"),
      item("ColorPicker", "Color selection input", "form"),
      item("FileUpload", "File picker input", "form"),
      item("DragDropUpload", "Drag-and-drop file zone", "form"),
    ],
  },
  {
    id: "typography",
    label: "Typography",
    icon: "🔤",
    defaultArchetype: "display",
    items: [
      item("Heading", "Semantic heading levels"),
      item("Text", "Body text block"),
      item("Paragraph", "Paragraph text"),
      item("Label", "Form field label"),
      item("Caption", "Small helper text"),
      item("Badge", "Compact status label"),
      item("Tag", "Removable tag label"),
      item("HighlightText", "Emphasized inline text"),
    ],
  },
  {
    id: "navigation",
    label: "Navigation",
    icon: "🧭",
    defaultArchetype: "navigation",
    items: [
      item("Navbar", "Top application navigation bar"),
      item("Sidebar", "Vertical side navigation"),
      item("Breadcrumb", "Hierarchical path links"),
      item("Pagination", "Page number navigation"),
      item("Tabs", "Tabbed content switcher"),
      item("Stepper", "Multi-step progress navigation"),
      item("MegaMenu", "Large dropdown navigation menu"),
      item("Drawer", "Slide-in navigation panel", "overlay"),
      item("BottomNavigation", "Mobile bottom tab bar"),
      item("CommandPalette", "Keyboard command launcher (Ctrl+K)"),
    ],
  },
  {
    id: "feedback",
    label: "Feedback Components",
    icon: "💬",
    defaultArchetype: "display",
    items: [
      item("Toast", "Transient toast notification"),
      item("Alert", "Inline alert banner"),
      item("Snackbar", "Bottom snack message"),
      item("Modal", "Modal dialog overlay", "overlay"),
      item("Dialog", "Generic dialog container", "overlay"),
      item("ConfirmationDialog", "Confirm/cancel dialog", "overlay"),
      item("Tooltip", "Hover tooltip", "overlay"),
      item("Popover", "Click-triggered popover", "overlay"),
      item("NotificationPanel", "Stacked notifications panel"),
    ],
  },
  {
    id: "loading",
    label: "Loading States",
    icon: "⏳",
    defaultArchetype: "display",
    items: [
      item("Spinner", "Indeterminate spinner"),
      item("ProgressBar", "Linear progress indicator"),
      item("CircularProgress", "Circular progress ring"),
      item("SkeletonLoader", "Content placeholder skeleton"),
      item("FullPageLoader", "Full viewport loading overlay", "overlay"),
      item("LazyImageLoader", "Image with lazy load placeholder", "media"),
    ],
  },
  {
    id: "data-display",
    label: "Data Display",
    icon: "📊",
    defaultArchetype: "data",
    items: [
      item("Card", "Content card container", "layout"),
      item("Avatar", "User avatar image"),
      item("Table", "Data table"),
      item("VirtualizedTable", "High-performance virtual table"),
      item("TreeView", "Hierarchical tree list"),
      item("Accordion", "Expandable sections"),
      item("Timeline", "Chronological event list"),
      item("List", "Vertical item list"),
      item("StatisticCard", "KPI statistic display", "dashboard"),
      item("EmptyState", "No-data placeholder"),
      item("KeyValueDisplay", "Label/value pairs"),
    ],
  },
  {
    id: "search",
    label: "Search Components",
    icon: "🔍",
    defaultArchetype: "search",
    items: [
      item("SearchBar", "Primary search input bar"),
      item("FilterPanel", "Faceted filter sidebar"),
      item("SortDropdown", "Sort order selector", "form-select"),
      item("AutoComplete", "Typeahead suggestions"),
      item("RecentSearches", "Recent query list"),
      item("SearchSuggestions", "Live search suggestions"),
    ],
  },
  {
    id: "dashboard",
    label: "Dashboard Components",
    icon: "📈",
    defaultArchetype: "dashboard",
    items: [
      item("KpiCard", "Key performance indicator card"),
      item("ChartContainer", "Chart wrapper container"),
      item("ActivityFeed", "Recent activity stream"),
      item("AnalyticsWidget", "Analytics summary widget"),
      item("CalendarWidget", "Mini calendar widget"),
      item("RecentActivity", "Compact activity list"),
    ],
  },
  {
    id: "authentication",
    label: "Authentication",
    icon: "🔐",
    defaultArchetype: "auth",
    items: [
      item("LoginForm", "User login form"),
      item("RegisterForm", "User registration form"),
      item("ForgotPassword", "Password reset request"),
      item("ResetPassword", "Set new password form"),
      item("OtpVerification", "OTP verification step"),
      item("SocialLoginButtons", "OAuth provider buttons", "button"),
    ],
  },
  {
    id: "layout",
    label: "Layout Components",
    icon: "📐",
    defaultArchetype: "layout",
    items: [
      item("Container", "Max-width page container"),
      item("Grid", "CSS grid layout"),
      item("Stack", "Vertical/horizontal stack"),
      item("FlexLayout", "Flexbox layout wrapper"),
      item("Section", "Page section block"),
      item("Divider", "Visual separator line"),
      item("Spacer", "Flexible spacing element"),
      item("ResponsiveWrapper", "Breakpoint-aware wrapper"),
    ],
  },
  {
    id: "tables",
    label: "Table Components",
    icon: "📋",
    defaultArchetype: "data",
    items: [
      item("SortableTable", "Column sortable data table"),
      item("EditableTable", "Inline editable cells"),
      item("ExpandableRows", "Rows with expand detail"),
      item("StickyHeader", "Table with sticky header"),
      item("StickyColumns", "Table with sticky columns"),
      item("InfiniteScrollTable", "Infinite scroll data table"),
      item("ServerPagination", "Server-driven pagination table"),
      item("RowSelection", "Multi-select row table"),
    ],
  },
  {
    id: "media",
    label: "Media Components",
    icon: "🖼️",
    defaultArchetype: "media",
    items: [
      item("Image", "Responsive image"),
      item("AvatarGroup", "Stacked avatar group"),
      item("ImageGallery", "Thumbnail image gallery"),
      item("Carousel", "Image/content carousel"),
      item("VideoPlayer", "Video playback control"),
      item("AudioPlayer", "Audio playback control"),
    ],
  },
  {
    id: "utility",
    label: "Utility Components",
    icon: "🛠️",
    defaultArchetype: "utility",
    items: [
      item("CopyToClipboard", "Copy text to clipboard"),
      item("QrCodeGenerator", "QR code display"),
      item("CountdownTimer", "Countdown clock display"),
      item("InfiniteScroll", "Infinite scroll container"),
      item("ScrollToTop", "Back-to-top button", "button"),
      item("BackButton", "Navigation back control", "button"),
      item("ThemeSwitcher", "Light/dark theme toggle", "button"),
      item("LanguageSwitcher", "Locale selector", "form-select"),
    ],
  },
  {
    id: "ecommerce",
    label: "E-commerce",
    icon: "🛒",
    defaultArchetype: "ecommerce",
    items: [
      item("ProductCard", "Product summary card"),
      item("ProductGallery", "Product image gallery", "media"),
      item("QuantitySelector", "Cart quantity stepper", "form"),
      item("PriceDisplay", "Formatted price label", "display"),
      item("Rating", "Star rating display", "display"),
      item("WishlistButton", "Add to wishlist control", "button"),
      item("CartBadge", "Cart item count badge", "display"),
      item("CouponInput", "Discount coupon field", "form"),
    ],
  },
  {
    id: "admin",
    label: "Admin Panel",
    icon: "⚙️",
    defaultArchetype: "admin",
    items: [
      item("UserCard", "User profile summary card", "data"),
      item("PermissionMatrix", "Role permission grid"),
      item("ActivityLog", "Admin activity log table", "data"),
      item("AuditTimeline", "Audit event timeline", "data"),
      item("StatusBadge", "Entity status badge", "display"),
      item("RoleSelector", "Role assignment dropdown", "form-select"),
    ],
  },
  {
    id: "advanced",
    label: "Advanced Components",
    icon: "🚀",
    defaultArchetype: "advanced",
    items: [
      item("RichTextEditor", "WYSIWYG rich text editor"),
      item("JsonViewer", "Read-only JSON tree viewer"),
      item("JsonEditor", "Editable JSON editor"),
      item("MarkdownEditor", "Markdown editor with preview"),
      item("CodeEditor", "Syntax-highlighted code editor"),
      item("KanbanBoard", "Drag-and-drop kanban board"),
      item("ResizablePanels", "Resizable panel group"),
      item("SplitPane", "Two-pane split layout", "layout"),
      item("FlowDiagram", "Node-based flow diagram"),
      item("OrganizationChart", "Org hierarchy chart"),
    ],
  },
];

export const CATALOG_CATEGORIES = COMPONENT_GROUPS.map((g) => ({
  id: g.id,
  slug: g.id,
  label: g.label,
  icon: g.icon,
}));
