import React from "react";
import styles from "./InfiniteScroll.module.css";

export interface InfiniteScrollProps {
  value?: string;
  disabled?: boolean;
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Infinite scroll container
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function InfiniteScroll({ value = "", disabled = false, children, onClick }: InfiniteScrollProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="infinite-scroll"
      type="button"
      onClick={onClick}
      disabled={disabled}
    >
      {children}
    </button>
    
  );
}

InfiniteScroll.displayName = "InfiniteScroll";
