import React from "react";
import styles from "./QrCodeGenerator.module.css";

export interface QrCodeGeneratorProps {
  value?: string;
  disabled?: boolean;
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * QR code display
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function QrCodeGenerator({ value = "", disabled = false, children, onClick }: QrCodeGeneratorProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="qr-code-generator"
      type="button"
      onClick={onClick}
      disabled={disabled}
    >
      {children}
    </button>
    
  );
}

QrCodeGenerator.displayName = "QrCodeGenerator";
