import React from "react";
import styles from "./SkeletonLoader.module.css";

export interface SkeletonLoaderProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Content placeholder skeleton
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function SkeletonLoader({ variant = "primary", size = "md", children, onClick }: SkeletonLoaderProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="skeleton-loader"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

SkeletonLoader.displayName = "SkeletonLoader";
