import React from "react";
import styles from "./KanbanBoard.module.css";

export interface KanbanBoardProps {
  value?: string;
  readOnly?: boolean;
  /** Editor height in px */
  height?: number;
  children?: React.ReactNode;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
}

/**
 * Drag-and-drop kanban board
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function KanbanBoard({ value = "", readOnly = false, height = 320, children, onChange }: KanbanBoardProps) {

  const inputId = React.useId();
  const errorId = `${inputId}-error`;
  return (
    <div className={styles.wrapper} data-testid="kanban-board">
      
      <input
        id={inputId}
        type="number"
        className={[styles.root].filter(Boolean).join(" ")}
        placeholder={placeholder}
        defaultValue={value}
        disabled={disabled}
        required={required}
        aria-required={required || undefined}
        onChange={onChange}
        onBlur={onBlur}
        aria-invalid={error ? true : undefined}
        aria-describedby={error ? errorId : undefined}
      />
      {error && (
        <span id={errorId} className={styles.error} role="alert">
          {error}
        </span>
      )}
    </div>
  );
}

KanbanBoard.displayName = "KanbanBoard";
