import React from "react";
import styles from "./Snackbar.module.css";

export interface SnackbarProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Bottom snack message
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Snackbar({ variant = "primary", size = "md", children, onClick }: SnackbarProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="snackbar"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Snackbar.displayName = "Snackbar";
