import React from "react";
import styles from "./KpiCard.module.css";

export interface KpiCardProps {
  /** Widget title */
  title?: string;
  /** Primary metric */
  value?: string;
  trend?: "up" | "down" | "neutral";
  /** Widget body */
  children?: React.ReactNode;
}

/**
 * Key performance indicator card
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function KpiCard({ title, value, trend = "neutral", children }: KpiCardProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="kpi-card"
      role="region"
    >
      {children}
    </div>
    
  );
}

KpiCard.displayName = "KpiCard";
