import React from "react";
import styles from "./SocialLoginButtons.module.css";

export interface SocialLoginButtonsProps {
  /** Visual style */
  variant?: "primary" | "secondary" | "ghost" | "danger";
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  loading?: boolean;
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * OAuth provider buttons
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function SocialLoginButtons({ variant = "primary", size = "md", disabled = false, loading = false, children, onClick }: SocialLoginButtonsProps) {
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onSubmit?.(event);
  };

  return (
    <form className={styles.root} data-testid="social-login-buttons" onSubmit={handleSubmit} noValidate>
      <h2 className={styles.title}>Social Login Buttons</h2>
      {error ? (
        <div className={styles.error} role="alert">
          {error}
        </div>
      ) : null}

      <label className={styles.field}>
        <span className={styles.label}>Variant</span>
        <select className={styles.input} defaultValue={variant} disabled>
          <option value="primary">primary</option>
          <option value="secondary">secondary</option>
          <option value="ghost">ghost</option>
          <option value="danger">danger</option>
        </select>
      </label>

      <label className={styles.field}>
        <span className={styles.label}>Size</span>
        <select className={styles.input} defaultValue={size} disabled>
          <option value="sm">sm</option>
          <option value="md">md</option>
          <option value="lg">lg</option>
        </select>
      </label>

      <label className={styles.fieldCheckbox}>
        <input type="checkbox" checked={disabled} readOnly className={styles.checkbox} />
        <span>Disabled</span>
      </label>

      <button type="submit" className={styles.submit} disabled={loading}>
        {loading ? "Please wait…" : "Submit"}
      </button>
    </form>
  );
}

SocialLoginButtons.displayName = "SocialLoginButtons";
