import React from "react";
import styles from "./UserCard.module.css";

export interface UserCardProps {
  variant?: "default" | "bordered" | "striped";
  loading?: boolean;
  empty?: boolean;
  /** Row or cell content */
  children?: React.ReactNode;
  /** Header area */
  header?: React.ReactNode;
  /** Footer area */
  footer?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * User profile summary card
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function UserCard({ variant = "default", loading = false, empty = false, children, header, footer, onClick }: UserCardProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="user-card"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

UserCard.displayName = "UserCard";
