import React from "react";
import styles from "./Popover.module.css";

export interface PopoverProps {
  /** Visibility */
  isOpen?: boolean;
  /** Title text */
  title?: string;
  /** Body content */
  children: React.ReactNode;
  onClose?: () => void;
}

/**
 * Click-triggered popover
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Popover({ isOpen = false, title, children, onClose }: PopoverProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="popover"
      role="dialog"
      onKeyDown={handleKeyDown}
    >
      {children}
    </div>
    
  );
}

Popover.displayName = "Popover";
