import React from "react";
import styles from "./Spinner.module.css";

export interface SpinnerProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Indeterminate spinner
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Spinner({ variant = "primary", size = "md", children, onClick }: SpinnerProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="spinner"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Spinner.displayName = "Spinner";
