import React from "react";
import styles from "./CartBadge.module.css";

export interface CartBadgeProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Cart item count badge
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function CartBadge({ variant = "primary", size = "md", children, onClick }: CartBadgeProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="cart-badge"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

CartBadge.displayName = "CartBadge";
