import React from "react";
import styles from "./Carousel.module.css";

export interface CarouselProps {
  /** Media source URL */
  src?: string;
  /** Accessible description */
  alt?: string;
  loading?: boolean;
  /** Caption or overlay */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Image/content carousel
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Carousel({ src, alt, loading = false, children, onClick }: CarouselProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="carousel"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

Carousel.displayName = "Carousel";
