import React from "react";
import styles from "./PriceDisplay.module.css";

export interface PriceDisplayProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Formatted price label
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function PriceDisplay({ variant = "primary", size = "md", children, onClick }: PriceDisplayProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="price-display"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

PriceDisplay.displayName = "PriceDisplay";
