import React from "react";
import styles from "./AudioPlayer.module.css";

export interface AudioPlayerProps {
  /** Media source URL */
  src?: string;
  /** Accessible description */
  alt?: string;
  loading?: boolean;
  /** Caption or overlay */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Audio playback control
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function AudioPlayer({ src, alt, loading = false, children, onClick }: AudioPlayerProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="audio-player"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

AudioPlayer.displayName = "AudioPlayer";
