import React from "react";
import styles from "./FullPageLoader.module.css";

export interface FullPageLoaderProps {
  /** Visibility */
  isOpen?: boolean;
  /** Title text */
  title?: string;
  /** Body content */
  children: React.ReactNode;
  onClose?: () => void;
}

/**
 * Full viewport loading overlay
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function FullPageLoader({ isOpen = false, title, children, onClose }: FullPageLoaderProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="full-page-loader"
      role="dialog"
      onKeyDown={handleKeyDown}
    >
      {children}
    </div>
    
  );
}

FullPageLoader.displayName = "FullPageLoader";
