import React from "react";
import styles from "./AvatarGroup.module.css";

export interface AvatarGroupProps {
  /** Media source URL */
  src?: string;
  /** Accessible description */
  alt?: string;
  loading?: boolean;
  /** Caption or overlay */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Stacked avatar group
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function AvatarGroup({ src, alt, loading = false, children, onClick }: AvatarGroupProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="avatar-group"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

AvatarGroup.displayName = "AvatarGroup";
