import React from "react";
import styles from "./ProgressBar.module.css";

export interface ProgressBarProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Linear progress indicator
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ProgressBar({ variant = "primary", size = "md", children, onClick }: ProgressBarProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="progress-bar"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

ProgressBar.displayName = "ProgressBar";
