import React from "react";
import styles from "./CircularProgress.module.css";

export interface CircularProgressProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Circular progress ring
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function CircularProgress({ variant = "primary", size = "md", children, onClick }: CircularProgressProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="circular-progress"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

CircularProgress.displayName = "CircularProgress";
