import React from "react";
import styles from "./Image.module.css";

export interface ImageProps {
  /** Media source URL */
  src?: string;
  /** Accessible description */
  alt?: string;
  loading?: boolean;
  /** Caption or overlay */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Responsive image
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Image({ src, alt, loading = false, children, onClick }: ImageProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="image"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

Image.displayName = "Image";
