import React from "react";
import styles from "./Link.module.css";

export interface LinkProps {
  variant?: "primary" | "secondary";
  disabled?: boolean;
  /** Content */
  children?: React.ReactNode;
}

/**
 * Styled anchor
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Link({ variant = "primary", disabled = false, children }: LinkProps) {

  return (
    
      <span
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="link"
      disabled={disabled}
      role="status"
    >
      {children}
    </span>
    
  );
}

Link.displayName = "Link";
