import React from "react";
import styles from "./OtpInput.module.css";

export interface OtpInputProps {
  /** Field label */
  label?: string;
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  /** Validation error message */
  error?: string;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
  onBlur?: (event: React.FocusEvent<HTMLInputElement>) => void;
}

/**
 * One-time password digits
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function OtpInput({ label, value = "", placeholder = "", disabled = false, required = false, error, onChange, onBlur }: OtpInputProps) {

  const inputId = React.useId();
  const errorId = `${inputId}-error`;
  return (
    <div className={styles.wrapper} data-testid="otp-input">
      <label className={styles.label} htmlFor={inputId}>
        {label}
      </label>
      <input
        id={inputId}
        type="text"
        className={[styles.root].filter(Boolean).join(" ")}
        placeholder={placeholder}
        defaultValue={value}
        disabled={disabled}
        required={required}
        aria-required={required || undefined}
        onChange={onChange}
        onBlur={onBlur}
        aria-invalid={error ? true : undefined}
        aria-describedby={error ? errorId : undefined}
      />
      {error && (
        <span id={errorId} className={styles.error} role="alert">
          {error}
        </span>
      )}
    </div>
  );
}

OtpInput.displayName = "OtpInput";
