import React from "react";
import styles from "./Tag.module.css";

export interface TagProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Removable tag label
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Tag({ variant = "primary", size = "md", children, onClick }: TagProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="tag"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Tag.displayName = "Tag";
