import React from "react";
import styles from "./AnalyticsWidget.module.css";

export interface AnalyticsWidgetProps {
  /** Widget title */
  title?: string;
  /** Primary metric */
  value?: string;
  trend?: "up" | "down" | "neutral";
  /** Widget body */
  children?: React.ReactNode;
}

/**
 * Analytics summary widget
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function AnalyticsWidget({ title, value, trend = "neutral", children }: AnalyticsWidgetProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="analytics-widget"
      role="region"
    >
      {children}
    </div>
    
  );
}

AnalyticsWidget.displayName = "AnalyticsWidget";
