import React from "react";
import styles from "./SearchBar.module.css";

export interface SearchBarProps {
  query?: string;
  placeholder?: string;
  loading?: boolean;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Primary search input bar
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function SearchBar({ query = "", placeholder = "Search…", loading = false, onChange, onClick }: SearchBarProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="search-bar"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      null
    </button>
    
  );
}

SearchBar.displayName = "SearchBar";
