import React from "react";
import styles from "./RegisterForm.module.css";

export interface RegisterFormProps {
  /** Full name */
  name?: string;
  /** Email address */
  email?: string;
  /** Password */
  password?: string;
  /** Confirm password */
  confirmPassword?: string;
  loading?: boolean;
  /** Form-level error */
  error?: string;
  onSubmit?: (event: React.FormEvent<HTMLFormElement>) => void;
}

/**
 * User registration form
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function RegisterForm({ name = "", email = "", password = "", confirmPassword = "", loading = false, error, onSubmit }: RegisterFormProps) {
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onSubmit?.(event);
  };

  return (
    <form className={styles.root} data-testid="register-form" onSubmit={handleSubmit} noValidate>
      <h2 className={styles.title}>Create account</h2>
      {error ? (
        <div className={styles.error} role="alert">
          {error}
        </div>
      ) : null}

      <label className={styles.field}>
        <span className={styles.label}>Name</span>
        <input
          type="text"
          className={styles.input}
          defaultValue={name}
          name="name"
          placeholder="Name"
          
        />
      </label>

      <label className={styles.field}>
        <span className={styles.label}>Email</span>
        <input
          type="email"
          className={styles.input}
          defaultValue={email}
          name="email"
          placeholder="Email"
          
        />
      </label>

      <label className={styles.field}>
        <span className={styles.label}>Password</span>
        <input
          type="password"
          className={styles.input}
          defaultValue={password}
          name="password"
          placeholder="Password"
          
        />
      </label>

      <label className={styles.field}>
        <span className={styles.label}>Confirm Password</span>
        <input
          type="password"
          className={styles.input}
          defaultValue={confirmPassword}
          name="confirmPassword"
          placeholder="Confirm Password"
          
        />
      </label>

      <button type="submit" className={styles.submit} disabled={loading}>
        {loading ? "Please wait…" : "Create account"}
      </button>
    </form>
  );
}

RegisterForm.displayName = "RegisterForm";
