import React from "react";
import styles from "./HighlightText.module.css";

export interface HighlightTextProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Emphasized inline text
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function HighlightText({ variant = "primary", size = "md", children, onClick }: HighlightTextProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="highlight-text"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

HighlightText.displayName = "HighlightText";
