import React from "react";
import styles from "./Container.module.css";

export interface ContainerProps {
  variant?: "default" | "compact" | "spacious";
  gap?: "sm" | "md" | "lg";
  /** Layout content */
  children: React.ReactNode;
}

/**
 * Max-width page container
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Container({ variant = "default", gap = "md", children }: ContainerProps) {

  return (
    
      <div
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="container"
      role="region"
    >
      {children}
    </div>
    
  );
}

Container.displayName = "Container";
