import React from "react";
import styles from "./RecentActivity.module.css";

export interface RecentActivityProps {
  /** Widget title */
  title?: string;
  /** Primary metric */
  value?: string;
  trend?: "up" | "down" | "neutral";
  /** Widget body */
  children?: React.ReactNode;
}

/**
 * Compact activity list
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function RecentActivity({ title, value, trend = "neutral", children }: RecentActivityProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="recent-activity"
      role="region"
    >
      {children}
    </div>
    
  );
}

RecentActivity.displayName = "RecentActivity";
