import React from "react";
import styles from "./NotificationPanel.module.css";

export interface NotificationPanelProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Stacked notifications panel
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function NotificationPanel({ variant = "primary", size = "md", children, onClick }: NotificationPanelProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="notification-panel"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

NotificationPanel.displayName = "NotificationPanel";
