import React from "react";
import styles from "./ChartContainer.module.css";

export interface ChartContainerProps {
  /** Widget title */
  title?: string;
  /** Primary metric */
  value?: string;
  trend?: "up" | "down" | "neutral";
  /** Widget body */
  children?: React.ReactNode;
}

/**
 * Chart wrapper container
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ChartContainer({ title, value, trend = "neutral", children }: ChartContainerProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="chart-container"
      role="region"
    >
      {children}
    </div>
    
  );
}

ChartContainer.displayName = "ChartContainer";
