import React from "react";
import styles from "./ProductCard.module.css";

export interface ProductCardProps {
  price?: number;
  currency?: string;
  quantity?: number;
  inStock?: boolean;
  /** Product details */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Product summary card
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ProductCard({ price = 0, currency = "USD", quantity = 1, inStock = true, children, onClick }: ProductCardProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="product-card"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

ProductCard.displayName = "ProductCard";
