import React from "react";
import styles from "./Progress.module.css";

export interface ProgressProps {
  variant?: "primary" | "secondary";
  disabled?: boolean;
  /** Content */
  children?: React.ReactNode;
}

/**
 * Progress indicator
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Progress({ variant = "primary", disabled = false, children }: ProgressProps) {

  return (
    
      <span
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="progress"
      disabled={disabled}
      role="status"
    >
      {children}
    </span>
    
  );
}

Progress.displayName = "Progress";
