import React from "react";
import styles from "./Stack.module.css";

export interface StackProps {
  variant?: "default" | "compact" | "spacious";
  gap?: "sm" | "md" | "lg";
  /** Layout content */
  children: React.ReactNode;
}

/**
 * Vertical/horizontal stack
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Stack({ variant = "default", gap = "md", children }: StackProps) {

  return (
    
      <div
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="stack"
      role="region"
    >
      {children}
    </div>
    
  );
}

Stack.displayName = "Stack";
