import React from "react";
import styles from "./Tooltip.module.css";

export interface TooltipProps {
  /** Visibility */
  isOpen?: boolean;
  /** Title text */
  title?: string;
  /** Body content */
  children: React.ReactNode;
  onClose?: () => void;
}

/**
 * Hover tooltip
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Tooltip({ isOpen = false, title, children, onClose }: TooltipProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="tooltip"
      role="dialog"
      onKeyDown={handleKeyDown}
    >
      {children}
    </div>
    
  );
}

Tooltip.displayName = "Tooltip";
