import React from "react";
import styles from "./Divider.module.css";

export interface DividerProps {
  variant?: "default" | "compact" | "spacious";
  gap?: "sm" | "md" | "lg";
  /** Layout content */
  children: React.ReactNode;
}

/**
 * Visual separator line
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Divider({ variant = "default", gap = "md", children }: DividerProps) {

  return (
    
      <div
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="divider"
      role="region"
    >
      {children}
    </div>
    
  );
}

Divider.displayName = "Divider";
