import React from "react";
import styles from "./FlexLayout.module.css";

export interface FlexLayoutProps {
  variant?: "default" | "compact" | "spacious";
  gap?: "sm" | "md" | "lg";
  /** Layout content */
  children: React.ReactNode;
}

/**
 * Flexbox layout wrapper
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function FlexLayout({ variant = "default", gap = "md", children }: FlexLayoutProps) {

  return (
    
      <div
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="flex-layout"
      role="region"
    >
      {children}
    </div>
    
  );
}

FlexLayout.displayName = "FlexLayout";
