import React from "react";
import styles from "./Accordion.module.css";

export interface AccordionProps {
  variant?: "default" | "bordered" | "striped";
  loading?: boolean;
  empty?: boolean;
  /** Row or cell content */
  children?: React.ReactNode;
  /** Header area */
  header?: React.ReactNode;
  /** Footer area */
  footer?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Expandable sections
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Accordion({ variant = "default", loading = false, empty = false, children, header, footer, onClick }: AccordionProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="accordion"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

Accordion.displayName = "Accordion";
