import React from "react";
import styles from "./StatisticCard.module.css";

export interface StatisticCardProps {
  /** Widget title */
  title?: string;
  /** Primary metric */
  value?: string;
  trend?: "up" | "down" | "neutral";
  /** Widget body */
  children?: React.ReactNode;
}

/**
 * KPI statistic display
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function StatisticCard({ title, value, trend = "neutral", children }: StatisticCardProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="statistic-card"
      role="region"
    >
      {children}
    </div>
    
  );
}

StatisticCard.displayName = "StatisticCard";
