import React from "react";
import styles from "./ResponsiveWrapper.module.css";

export interface ResponsiveWrapperProps {
  variant?: "default" | "compact" | "spacious";
  gap?: "sm" | "md" | "lg";
  /** Layout content */
  children: React.ReactNode;
}

/**
 * Breakpoint-aware wrapper
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ResponsiveWrapper({ variant = "default", gap = "md", children }: ResponsiveWrapperProps) {

  return (
    
      <div
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="responsive-wrapper"
      role="region"
    >
      {children}
    </div>
    
  );
}

ResponsiveWrapper.displayName = "ResponsiveWrapper";
