import React from "react";
import styles from "./Drawer.module.css";

export interface DrawerProps {
  /** Visibility */
  isOpen?: boolean;
  /** Title text */
  title?: string;
  /** Body content */
  children: React.ReactNode;
  onClose?: () => void;
}

/**
 * Slide-in navigation panel
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Drawer({ isOpen = false, title, children, onClose }: DrawerProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="drawer"
      role="dialog"
      onKeyDown={handleKeyDown}
    >
      {children}
    </div>
    
  );
}

Drawer.displayName = "Drawer";
