import React from "react";
import styles from "./Text.module.css";

export interface TextProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Body text block
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Text({ variant = "primary", size = "md", children, onClick }: TextProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="text"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Text.displayName = "Text";
