import React from "react";
import styles from "./Section.module.css";

export interface SectionProps {
  variant?: "default" | "compact" | "spacious";
  gap?: "sm" | "md" | "lg";
  /** Layout content */
  children: React.ReactNode;
}

/**
 * Page section block
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Section({ variant = "default", gap = "md", children }: SectionProps) {

  return (
    
      <div
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="section"
      role="region"
    >
      {children}
    </div>
    
  );
}

Section.displayName = "Section";
