import React from "react";
import styles from "./LazyImageLoader.module.css";

export interface LazyImageLoaderProps {
  /** Media source URL */
  src?: string;
  /** Accessible description */
  alt?: string;
  loading?: boolean;
  /** Caption or overlay */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Image with lazy load placeholder
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function LazyImageLoader({ src, alt, loading = false, children, onClick }: LazyImageLoaderProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="lazy-image-loader"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

LazyImageLoader.displayName = "LazyImageLoader";
