import React from "react";
import styles from "./ActivityFeed.module.css";

export interface ActivityFeedProps {
  /** Widget title */
  title?: string;
  /** Primary metric */
  value?: string;
  trend?: "up" | "down" | "neutral";
  /** Widget body */
  children?: React.ReactNode;
}

/**
 * Recent activity stream
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ActivityFeed({ title, value, trend = "neutral", children }: ActivityFeedProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="activity-feed"
      role="region"
    >
      {children}
    </div>
    
  );
}

ActivityFeed.displayName = "ActivityFeed";
