import React from "react";
import styles from "./StatusBadge.module.css";

export interface StatusBadgeProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Entity status badge
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function StatusBadge({ variant = "primary", size = "md", children, onClick }: StatusBadgeProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="status-badge"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

StatusBadge.displayName = "StatusBadge";
