import React from "react";
import styles from "./Caption.module.css";

export interface CaptionProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Small helper text
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Caption({ variant = "primary", size = "md", children, onClick }: CaptionProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="caption"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Caption.displayName = "Caption";
