import React from "react";
import styles from "./Grid.module.css";

export interface GridProps {
  variant?: "default" | "compact" | "spacious";
  gap?: "sm" | "md" | "lg";
  /** Layout content */
  children: React.ReactNode;
}

/**
 * CSS grid layout
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Grid({ variant = "default", gap = "md", children }: GridProps) {

  return (
    
      <div
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="grid"
      role="region"
    >
      {children}
    </div>
    
  );
}

Grid.displayName = "Grid";
