import React from "react";
import styles from "./Badge.module.css";

export interface BadgeProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Compact status label
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Badge({ variant = "primary", size = "md", children, onClick }: BadgeProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="badge"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Badge.displayName = "Badge";
