import React from "react";
import styles from "./BackButton.module.css";

export interface BackButtonProps {
  /** Visual style */
  variant?: "primary" | "secondary" | "ghost" | "danger";
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  loading?: boolean;
  /** Button label */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Navigation back control
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function BackButton({ variant = "primary", size = "md", disabled = false, loading = false, children, onClick }: BackButtonProps) {

  const handleKeyDown = (event: React.KeyboardEvent<HTMLElement>) => {
    if (["Enter", " "].includes(event.key) && onClick) {
      event.preventDefault();
      onClick(event as unknown as React.MouseEvent<HTMLElement>);
    }
  };
  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="back-button"
      type="button"
      onClick={onClick}
      disabled={disabled}
      aria-busy={loading}
      onKeyDown={handleKeyDown}
    >
      {children}
    </button>
    
  );
}

BackButton.displayName = "BackButton";
