import React from "react";
import styles from "./CopyToClipboard.module.css";

export interface CopyToClipboardProps {
  value?: string;
  disabled?: boolean;
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Copy text to clipboard
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function CopyToClipboard({ value = "", disabled = false, children, onClick }: CopyToClipboardProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="copy-to-clipboard"
      type="button"
      onClick={onClick}
      disabled={disabled}
    >
      {children}
    </button>
    
  );
}

CopyToClipboard.displayName = "CopyToClipboard";
