import React from "react";
import styles from "./ResetPassword.module.css";

export interface ResetPasswordProps {
  /** New password */
  password?: string;
  /** Confirm password */
  confirmPassword?: string;
  loading?: boolean;
  /** Form-level error */
  error?: string;
  onSubmit?: (event: React.FormEvent<HTMLFormElement>) => void;
}

/**
 * Set new password form
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ResetPassword({ password = "", confirmPassword = "", loading = false, error, onSubmit }: ResetPasswordProps) {
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onSubmit?.(event);
  };

  return (
    <form className={styles.root} data-testid="reset-password" onSubmit={handleSubmit} noValidate>
      <h2 className={styles.title}>Reset password</h2>
      {error ? (
        <div className={styles.error} role="alert">
          {error}
        </div>
      ) : null}

      <label className={styles.field}>
        <span className={styles.label}>Password</span>
        <input
          type="password"
          className={styles.input}
          defaultValue={password}
          name="password"
          placeholder="Password"
          
        />
      </label>

      <label className={styles.field}>
        <span className={styles.label}>Confirm Password</span>
        <input
          type="password"
          className={styles.input}
          defaultValue={confirmPassword}
          name="confirmPassword"
          placeholder="Confirm Password"
          
        />
      </label>

      <button type="submit" className={styles.submit} disabled={loading}>
        {loading ? "Please wait…" : "Update password"}
      </button>
    </form>
  );
}

ResetPassword.displayName = "ResetPassword";
