import React from "react";
import styles from "./OtpVerification.module.css";

export interface OtpVerificationProps {
  /** 6-digit verification code */
  code?: string;
  loading?: boolean;
  /** Form-level error */
  error?: string;
  onSubmit?: (event: React.FormEvent<HTMLFormElement>) => void;
}

/**
 * OTP verification step
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function OtpVerification({ code = "", loading = false, error, onSubmit }: OtpVerificationProps) {
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onSubmit?.(event);
  };

  return (
    <form className={styles.root} data-testid="otp-verification" onSubmit={handleSubmit} noValidate>
      <h2 className={styles.title}>Verify your code</h2>
      {error ? (
        <div className={styles.error} role="alert">
          {error}
        </div>
      ) : null}

      <label className={styles.field}>
        <span className={styles.label}>Code</span>
        <input
          type="text"
          className={styles.input}
          defaultValue={code}
          name="code"
          placeholder="Code"
           maxLength={6} autoComplete="one-time-code"
        />
      </label>

      <button type="submit" className={styles.submit} disabled={loading}>
        {loading ? "Please wait…" : "Verify"}
      </button>
    </form>
  );
}

OtpVerification.displayName = "OtpVerification";
