import React from "react";
import styles from "./Pill.module.css";

export interface PillProps {
  variant?: "primary" | "secondary";
  disabled?: boolean;
  /** Content */
  children?: React.ReactNode;
}

/**
 * Rounded status pill
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Pill({ variant = "primary", disabled = false, children }: PillProps) {

  return (
    
      <span
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="pill"
      disabled={disabled}
      role="status"
    >
      {children}
    </span>
    
  );
}

Pill.displayName = "Pill";
