import React from "react";
import styles from "./Paragraph.module.css";

export interface ParagraphProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Paragraph text
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Paragraph({ variant = "primary", size = "md", children, onClick }: ParagraphProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="paragraph"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Paragraph.displayName = "Paragraph";
