import React from "react";
import styles from "./ConfirmationDialog.module.css";

export interface ConfirmationDialogProps {
  /** Visibility */
  isOpen?: boolean;
  /** Title text */
  title?: string;
  /** Body content */
  children: React.ReactNode;
  onClose?: () => void;
}

/**
 * Confirm/cancel dialog
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ConfirmationDialog({ isOpen = false, title, children, onClose }: ConfirmationDialogProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="confirmation-dialog"
      role="dialog"
      onKeyDown={handleKeyDown}
    >
      {children}
    </div>
    
  );
}

ConfirmationDialog.displayName = "ConfirmationDialog";
