import React from "react";
import styles from "./Dialog.module.css";

export interface DialogProps {
  /** Visibility */
  isOpen?: boolean;
  /** Title text */
  title?: string;
  /** Body content */
  children: React.ReactNode;
  onClose?: () => void;
}

/**
 * Generic dialog container
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Dialog({ isOpen = false, title, children, onClose }: DialogProps) {

  return (
    
      <div
      className={[styles.root].filter(Boolean).join(" ")} data-testid="dialog"
      role="dialog"
      onKeyDown={handleKeyDown}
    >
      {children}
    </div>
    
  );
}

Dialog.displayName = "Dialog";
