import React from "react";
import styles from "./Toast.module.css";

export interface ToastProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Transient toast notification
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Toast({ variant = "primary", size = "md", children, onClick }: ToastProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="toast"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Toast.displayName = "Toast";
