import React from "react";
import styles from "./Heading.module.css";

export interface HeadingProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Semantic heading levels
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Heading({ variant = "primary", size = "md", children, onClick }: HeadingProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="heading"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Heading.displayName = "Heading";
