import React from "react";
import styles from "./Chip.module.css";

export interface ChipProps {
  variant?: "primary" | "secondary";
  disabled?: boolean;
  /** Content */
  children?: React.ReactNode;
}

/**
 * Choice chip
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Chip({ variant = "primary", disabled = false, children }: ChipProps) {

  return (
    
      <span
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="chip"
      disabled={disabled}
      role="status"
    >
      {children}
    </span>
    
  );
}

Chip.displayName = "Chip";
