import React from "react";
import styles from "./Textarea.module.css";

export interface TextareaProps {
  /** Field label */
  label?: string;
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  /** Validation error message */
  error?: string;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
  onBlur?: (event: React.FocusEvent<HTMLInputElement>) => void;
}

/**
 * Multi-line text input
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Textarea({ label, value = "", placeholder = "", disabled = false, required = false, error, onChange, onBlur }: TextareaProps) {

  const inputId = React.useId();
  const errorId = `${inputId}-error`;
  return (
    <div className={styles.wrapper} data-testid="textarea">
      <label className={styles.label} htmlFor={inputId}>
        {label}
      </label>
      <textarea
        id={inputId}
        className={[styles.root].filter(Boolean).join(" ")}
        placeholder={placeholder}
        defaultValue={value}
        disabled={disabled}
        onChange={onChange}
        rows={4}
      />
    </div>
  );
}

Textarea.displayName = "Textarea";
