import React from "react";
import styles from "./ImageGallery.module.css";

export interface ImageGalleryProps {
  /** Media source URL */
  src?: string;
  /** Accessible description */
  alt?: string;
  loading?: boolean;
  /** Caption or overlay */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Thumbnail image gallery
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ImageGallery({ src, alt, loading = false, children, onClick }: ImageGalleryProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="image-gallery"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

ImageGallery.displayName = "ImageGallery";
