import React from "react";
import styles from "./ForgotPassword.module.css";

export interface ForgotPasswordProps {
  /** Email address */
  email?: string;
  loading?: boolean;
  /** Form-level error */
  error?: string;
  onSubmit?: (event: React.FormEvent<HTMLFormElement>) => void;
}

/**
 * Password reset request
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ForgotPassword({ email = "", loading = false, error, onSubmit }: ForgotPasswordProps) {
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onSubmit?.(event);
  };

  return (
    <form className={styles.root} data-testid="forgot-password" onSubmit={handleSubmit} noValidate>
      <h2 className={styles.title}>Forgot password</h2>
      {error ? (
        <div className={styles.error} role="alert">
          {error}
        </div>
      ) : null}

      <label className={styles.field}>
        <span className={styles.label}>Email</span>
        <input
          type="email"
          className={styles.input}
          defaultValue={email}
          name="email"
          placeholder="Email"
          
        />
      </label>

      <button type="submit" className={styles.submit} disabled={loading}>
        {loading ? "Please wait…" : "Send reset link"}
      </button>
    </form>
  );
}

ForgotPassword.displayName = "ForgotPassword";
