import React from "react";
import styles from "./SplitPane.module.css";

export interface SplitPaneProps {
  variant?: "default" | "compact" | "spacious";
  gap?: "sm" | "md" | "lg";
  /** Layout content */
  children: React.ReactNode;
}

/**
 * Two-pane split layout
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function SplitPane({ variant = "default", gap = "md", children }: SplitPaneProps) {

  return (
    
      <div
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="split-pane"
      role="region"
    >
      {children}
    </div>
    
  );
}

SplitPane.displayName = "SplitPane";
