import React from "react";
import styles from "./Rating.module.css";

export interface RatingProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Star rating display
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Rating({ variant = "primary", size = "md", children, onClick }: RatingProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="rating"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Rating.displayName = "Rating";
