import React from "react";
import styles from "./VideoPlayer.module.css";

export interface VideoPlayerProps {
  /** Media source URL */
  src?: string;
  /** Accessible description */
  alt?: string;
  loading?: boolean;
  /** Caption or overlay */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Video playback control
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function VideoPlayer({ src, alt, loading = false, children, onClick }: VideoPlayerProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="video-player"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

VideoPlayer.displayName = "VideoPlayer";
