import React from "react";
import styles from "./Label.module.css";

export interface LabelProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Form field label
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Label({ variant = "primary", size = "md", children, onClick }: LabelProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="label"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Label.displayName = "Label";
