import React from "react";
import styles from "./ProductGallery.module.css";

export interface ProductGalleryProps {
  /** Media source URL */
  src?: string;
  /** Accessible description */
  alt?: string;
  loading?: boolean;
  /** Caption or overlay */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Product image gallery
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function ProductGallery({ src, alt, loading = false, children, onClick }: ProductGalleryProps) {

  return (
    
      <button
      className={[styles.root].filter(Boolean).join(" ")} data-testid="product-gallery"
      type="button"
      onClick={onClick}
      aria-busy={loading}
    >
      {children}
    </button>
    
  );
}

ProductGallery.displayName = "ProductGallery";
