import React from "react";
import styles from "./Spacer.module.css";

export interface SpacerProps {
  variant?: "default" | "compact" | "spacious";
  gap?: "sm" | "md" | "lg";
  /** Layout content */
  children: React.ReactNode;
}

/**
 * Flexible spacing element
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Spacer({ variant = "default", gap = "md", children }: SpacerProps) {

  return (
    
      <div
      className={[styles.root, variant && styles[variant]].filter(Boolean).join(" ")} data-testid="spacer"
      role="region"
    >
      {children}
    </div>
    
  );
}

Spacer.displayName = "Spacer";
