import React from "react";
import styles from "./Alert.module.css";

export interface AlertProps {
  variant?: "primary" | "secondary" | "success" | "warning" | "error";
  size?: "sm" | "md" | "lg";
  /** Content */
  children?: React.ReactNode;
  onClick?: (event: React.MouseEvent<HTMLElement>) => void;
}

/**
 * Inline alert banner
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function Alert({ variant = "primary", size = "md", children, onClick }: AlertProps) {

  return (
    
      <button
      className={[styles.root, variant && styles[variant], size && styles[size]].filter(Boolean).join(" ")} data-testid="alert"
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
    
  );
}

Alert.displayName = "Alert";
