import React from "react";
import styles from "./LoginForm.module.css";

export interface LoginFormProps {
  /** Email address */
  email?: string;
  /** Password */
  password?: string;
  rememberMe?: boolean;
  loading?: boolean;
  /** Form-level error */
  error?: string;
  onSubmit?: (event: React.FormEvent<HTMLFormElement>) => void;
}

/**
 * User login form
 * @generated by Component Forge — edit schema and re-run forge generate
 */
export function LoginForm({ email = "", password = "", rememberMe = false, loading = false, error, onSubmit }: LoginFormProps) {
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onSubmit?.(event);
  };

  return (
    <form className={styles.root} data-testid="login-form" onSubmit={handleSubmit} noValidate>
      <h2 className={styles.title}>Sign in</h2>
      {error ? (
        <div className={styles.error} role="alert">
          {error}
        </div>
      ) : null}

      <label className={styles.field}>
        <span className={styles.label}>Email</span>
        <input
          type="email"
          className={styles.input}
          defaultValue={email}
          name="email"
          placeholder="Email"
          
        />
      </label>

      <label className={styles.field}>
        <span className={styles.label}>Password</span>
        <input
          type="password"
          className={styles.input}
          defaultValue={password}
          name="password"
          placeholder="Password"
          
        />
      </label>

      <label className={styles.fieldCheckbox}>
        <input type="checkbox" checked={rememberMe} readOnly className={styles.checkbox} />
        <span>Remember Me</span>
      </label>

      <button type="submit" className={styles.submit} disabled={loading}>
        {loading ? "Please wait…" : "Sign in"}
      </button>
    </form>
  );
}

LoginForm.displayName = "LoginForm";
